### ISSUE TITLE
The Operator could watch objects it depends on to reconcile

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/messaging-topology-operator#126]
Some kinds e.g. User depend on a user provided Secret. CRUD operations to this secret won't trigger a reconcile loop, which in turn results in the Secret containing information that doesn't match RabbitMQ's internal database. To "force a sync", a user has to modify the kind in question, for example, by adding a label.

The Operator could watch those external objects and trigger a reconcile on update of external resources.

**Comment by ChunyiLyu** [comment]
This enhancement applies to `federations.rabbitmq.com`.

**Comment by Zerpet** [comment]
I'd like to see this enhancement into all kinds that reference a Secret in their spec. This caught me a few times while working with `schemareplication` kind, but I can see benefit of adding this to all other kinds.
