### ISSUE TITLE
Previous releases (ex v0.6.0) manifests point to :latest image causing it to always fail to deploy

### ISSUE THREAD

**Issue by mylesagray** [rabbitmq/messaging-topology-operator#181]
## Describe the bug
If you deploy the v0.6.0 manifests here: https://github.com/rabbitmq/messaging-topology-operator/releases/tag/v0.6.0 it will fail to come up as the manifests point to the `:latest` version of the container image, which is expecting CRDs that we're introduced until v0.9.0 to be present, causing the container to be in a perpetual "ContainerCreating" fail loop.

I am using v0.6.0 as that is required by the product I am installing (CNR v0.2.0).

Possibly related to #180 

## To Reproduce
`kubectl apply -f https://github.com/rabbitmq/messaging-topology-operator/releases/tag/v0.6.0` on a fresh cluster that's never had a newer version of the topology operator installed.

It will never come up.

**Expected behavior**
The operator releases should always work - Images in released manifests should always be tagged, never `:latest` to avoid this problem.

## Version and environment information
- Messaging Topology Operator: 0.6.0
- RabbitMQ: /
- RabbitMQ Cluster Operator: 1.6.0
- Kubernetes: 1.20.2
- Cloud provider or hardware configuration: vSphere with Tanzu

**Comment by ChunyiLyu** [comment]
@mylesagray this was a known issue.  The image tag issue is corrected from `0.7.0` onwards and please upgrade to the latest messaging topology operator. We won't release patches for past minor versions.
