### ISSUE TITLE
Exchanges definition - Allow other types from plugins such as rabbitmq-consistent-hash-exchange

### ISSUE THREAD

**Issue by Lebvanih** [rabbitmq/messaging-topology-operator#192]
**Is your feature request related to a problem? Please describe.**
We are currently migration from our old RabbitMQ chart to the Operator, however, we are not able to migrate some of the exchange as they use the following plugin: https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange
We are getting the following error: 
> The Exchange "rabbitmq-cluster-event" is invalid: spec.type: Unsupported value: "x-consistent-hash": supported values: "direct", "fanout", "headers", "topic"

If I check in the CRD definition I see that there is a list that is mentioned as enum. I assume this is done to ensure the validation.
```              
type:
 default: direct
 description: Cannot be updated
 enum:
     - direct
     - fanout
     - headers
     - topic
```
**Describe the solution you'd like**
We would like to have the option to declare these exchange directly via the operator. Considering the plugin is from the rabbitmq github project, we would like to have that possibility.
**Describe alternatives you've considered**
We tried to alter the manifest of the CRD to add that type of exchange in the enum list. And it seems to work, the exchange is properly creatd. However, we will have to patch it again after every update of the CRD. If a more permanent solution could be provided, this would be better for us. And this could affect other plugins (that we aren't using)
The alternate solution that we have is to create these exchange outside of the CRD via K8S job as we did in the past, but this defeat a bit the purpose of switching to the CRD for us.

**Additional context**
N/A

**Comment by ChunyiLyu** [comment]
@Lebvanih Good point indeed. I missed exchange types like consistent hash or sharding when implementing it. Removing the accepted exchange type list all together would be the best for flexibility going forward. Will discuss with the team and ping you afterwards.

**Comment by ChunyiLyu** [comment]
Hi @Lebvanih , a new release which removes the constraint on exchange type was just cut. Feel free to try it out and let us know whether it fixes the issue. https://github.com/rabbitmq/messaging-topology-operator/releases/tag/v0.11.0

**Comment by Lebvanih** [comment]
Hi @ChunyiLyu , 

I updated the Operator on our side and all seems good! No more issues.
Thank you!
