### ISSUE TITLE
Unable to delete User if not fully created

### ISSUE THREAD

**Issue by twhite0** [rabbitmq/messaging-topology-operator#195]
## Describe the bug
Unable to delete a `User` if it fails creation.  Related to: https://github.com/rabbitmq/messaging-topology-operator/issues/194

```bash
$ oc describe user.rabbitmq.com worker
Name:         worker
Namespace:    psa-dev
Labels:       <none>
Annotations:  <none>
API Version:  rabbitmq.com/v1beta1
Kind:         User
....
Events:
  Type     Reason        Age                 From             Message
  ----     ------        ----                ----             -------
  Warning  FailedDelete  4m6s (x2 over 12m)  user-controller  failed to retrieve user credentials secret from status
```

## To Reproduce
In failing to properly create the `User` via: https://github.com/rabbitmq/messaging-topology-operator/issues/194,   
Force deleting (--force) also fails to remove it.

**Expected behavior**
Able to remove the resource.

## Version and environment information
- Messaging Topology Operator: **rabbitmqoperator/messaging-topology-operator:0.10.0**
- RabbitMQ: **rabbitmq:3.8.18-management**
- RabbitMQ Cluster Operator: **rabbitmqoperator/cluster-operator:1.8.0**
- Kubernetes: **v1.19.0+a5a0987**
- Cloud provider or hardware configuration: **OpenShift 4.6.26**

**Comment by twhite0** [comment]
Here is the topology logs:

```
2021-07-21T22:41:02.408Z	INFO	controller-runtime.manager.controller.user	Deleting	{"reconciler group": "rabbitmq.com", "reconciler kind": "User", "name": "worker", "namespace": "psa-dev"}
2021-07-21T22:41:02.408Z	ERROR	controller-runtime.manager.controller.user	failed to retrieve user credentials secret from status	{"reconciler group": "rabbitmq.com", "reconciler kind": "User", "name": "worker", "namespace": "psa-dev", "user.status": {}, "error": "this User does not yet have a Credentials Secret created"}
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).Reconcile
	/workspace/controllers/user_controller.go:94
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
2021-07-21T22:41:02.408Z	ERROR	controller-runtime.manager.controller.user	Reconciler error	{"reconciler group": "rabbitmq.com", "reconciler kind": "User", "name": "worker", "namespace": "psa-dev", "error": "this User does not yet have a Credentials Secret created"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
2021-07-21T22:41:02.408Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"User","namespace":"psa-dev","name":"worker","uid":"40d5f97f-1706-4b03-9afe-bba017a01387","apiVersion":"rabbitmq.com/v1beta1","resourceVersion":"457760688"}, "reason": "FailedDelete", "message": "failed to retrieve user credentials secret from status"}
```

**Comment by twhite0** [comment]
I was able to delete the resource by patching the finalizer:

`oc patch user.rabbitmq.com/worker -p '{"metadata":{"finalizers":[]}}' --type=merge`

**Comment by ChunyiLyu** [comment]
Hi @twhite0, I can reproduce the same error when I delete a user after manually deleting the corresponding k8s secret object. Will look into how to handle this gracefully. Thanks for spotting this issue.

**Comment by matheusgiuliano** [comment]
> I was able to delete the resource by patching the finalizer:
> 
> `oc patch user.rabbitmq.com/worker -p '{"metadata":{"finalizers":[]}}' --type=merge`

I had to do the same with a Policy

**Comment by eduardomb08** [comment]
I have the same problem

**Comment by JoostvdB94** [comment]
This is still an issue. We ran into this issue after incorrectly configuring the namespace in the user definition. 
It stated that it had failed to generate the credentials. Deleting the user did nothing, and even trying to force delete it dit not work.

Can we re-open this issue?

**Comment by egeorges92** [comment]
Bonjour,

my solution was to run finalizers patch (as describe below) to user and user permissions :

``
kubectl patch user.rabbitmq.com/myUser -p '{"metadata":{"finalizers":[]}}' --type=merge -n myNamespace
kubectl patch permission.rabbitmq.com/myUserPermission1 -p '{"metadata":{"finalizers":[]}}' --type=merge -n myNamespace
# other permissions
...
``
