### ISSUE TITLE
Does it make sense for the operator to use `default_user` from RabbitmqCluster

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/messaging-topology-operator#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MirahImage** [comment]
An alternative would be to (either directly or via an agent within the RMQ cluster) pod-exec into the RabbitMQ cluster and have the commands executed locally. However, this seems like it would have just as many, if not more, security risks as using the default_user. 

Additionally, if we were to attempt to make this process more secure, for example by requiring mTLS between the topology operator and the cluster, it would significantly complicate the deployment process.
