### ISSUE TITLE
cert-manager should not be a hard requirement

### ISSUE THREAD

**Issue by benmoss** [rabbitmq/messaging-topology-operator#245]
**Is your feature request related to a problem? Please describe.**
As an operator I'd prefer not to have to install cert-manager if I'm not trying to do anything fancy with certificate management.

**Describe the solution you'd like**
A documented way for users to bring their own certificates, but not necessarily via cert-manager.

**Additional context**
[Strimzi](https://strimzi.io/) is a comparable operator for managing Kafka clusters. They do not have a dependency on cert-manager and [this](https://strimzi.io/docs/operators/latest/using.html#installing-your-own-ca-certificates-str) is their documentation for how to manage your own certificates.

It seems like it automatically can provision its own certificates, but in the case of bring-your-own it just expects the user to provide Kubernetes secrets containing the certificates and keys. A user could use cert-manager to create these and still get the benefits of cert-manager, or whatever certificate management system they want.

**Comment by ChunyiLyu** [comment]
Hi @benmoss, I'm going to convert this issue to a github discussion because it seems to be more of a question 😄
