### ISSUE TITLE
CR Deletion through kubectl hangs when the referenced RabbitmqCluster object was deleted

### ISSUE THREAD

**Issue by coro** [rabbitmq/messaging-topology-operator#30]
For all of the controllers at time of writing, the rabbitholeClient is generated first, at the start of the Reconcile loop, in order to fulfil the finaliser functionality. The generation of this client relies on the RabbitmqCluster object referenced in the object Spec to exist, failing if it does not.

If the referenced RabbitmqCluster object is deleted before any topology CRs are deleted, any attempts to delete the CRs will hang, as the Reconcile will fail due to its inability to create a rabbitholeClient to a Cluster that no longer exists.

It's worth thinking about what the user experience should be here. As a user, I would like to not have to delete my resources in a specific order in order to stand up a new cluster with new topology CRs. I would also like for my topology CRs to persist even if the underlying cluster goes down (e.g. in the event of replacing the whole cluster deployment with a new cluster).

**Comment by MirahImage** [comment]
Is this now solved by #52?

**Comment by coro** [comment]
Yep, closing.
