### ISSUE TITLE
Support updates to User resources & credential Secrets

### ISSUE THREAD

**Issue by coro** [rabbitmq/messaging-topology-operator#35]
**Is your feature request related to a problem? Please describe.**
Currently, User objects can only be created and deleted, but not updated. 

**Describe the solution you'd like**
### Editing the User
- Changing User.Spec.Name or User.Spec.RabbitmqClusterReference: TBD, but probably reject the request with a validating webhook, rather than delete the existing user and create a new one. Otherwise, an app consuming the User Secret will have to reload the secret to regain access to an authenticated user.
- Changing User.Spec.Tags: Updates the tags associated with a user.

### Editing the User Secret
- Changing Secret.Data["username"]: TBD, but again probably reject the request
- Changing Secret.Data["password"]: Calculate a new password hash and update the user

**Additional context**
Original Issue: #3

**Comment by carlosjgp** [comment]
could we reopen this?

**Comment by cronventis** [comment]
Please implement :)
