### ISSUE TITLE
Error: API responded with a 401 Unauthorized

### ISSUE THREAD

**Issue by vinu1421** [rabbitmq/messaging-topology-operator#365]
When trying to add a new user I am facing some issues

```
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: admin
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: xxx
  importCredentialsSecret:
    name: rabbitmq-admin
```

I am getting below error
```
{"level":"error","ts":1652114224.668113,"logger":"controller.user","msg":"failed to declare user","reconciler group":"rabbitmq.com","reconciler kind":"User","name":"admin","namespace":"xxx","user":"admin","error":"Error: API responded with a 401 Unauthorized","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227"}
```
```
"error":"Error: API responded with a 401 Unauthorized"
```
```
Status:
  Conditions:
    Last Transition Time:  2022-05-10T12:28:08Z
    Message:               Error: API responded with a 401 Unauthorized
    Reason:                FailedCreateOrUpdate
    Status:                False
    Type:                  Ready
  Credentials:
    Name:  admin-user-credentials
Events:
  Type     Reason         Age                 From             Message
  ----     ------         ----                ----             -------
  Warning  FailedDeclare  35m (x22 over 71m)  user-controller  failed to declare user
  Warning  FailedDeclare  12s (x13 over 33s)  user-controller  failed to declare user
```

Also noted the below error on rabbitmq pod, not sure this is related. 

```
2022-05-10 14:57:08.036 [warning] <0.604.68> HTTP access denied: user 'default_user_gywGvxsWeFokyRe_mUy' - invalid credentials
15
2022-05-10 14:57:08.052 [warning] <0.610.68> HTTP access denied: user 'default_user_gywGvxsWeFokyRe_mUy' - invalid credentials
14
2022-05-10 14:57:08.068 [warning] <0.609.68> HTTP access denied: user 'default_user_gywGvxsWeFokyRe_mUy' - invalid credentials
13
2022-05-10 14:57:08.085 [warning] <0.608.68> HTTP access denied: user 'default_user_gywGvxsWeFokyRe_mUy' - invalid credentials
12
2022-05-10 14:57:08.181 [warning] <0.616.68> HTTP access denied: user 'default_user_gywGvxsWeFokyRe_mUy' - invalid credentials
11
2022-05-10 14:57:08.356 [warning] <0.621.68> HTTP access denied: user 'default_user_gywGvxsWeFokyRe_mUy' - invalid credentials
10

```

## Version and environment information
- Messaging Topology Operator: 1.4.0
- RabbitMQ: 3.8.21-management
- RabbitMQ Cluster Operator: 1.10.0
- Kubernetes: v1.21.10-gke.1300

**Comment by ChunyiLyu** [comment]
Logs suggest that the topology operator failed because the user failed to authenticate with the RabbitMQ server. Please check if you could use the default user credentials to authenticate with the RabbitMQ server. You can find your default user credentials by following https://www.rabbitmq.com/kubernetes/operator/using-operator.html#creds

**Comment by vinu1421** [comment]
@ChunyiLyu Where should we configure the credentials in the topology operator?  I didn't find anything in the documentation.

**Comment by ChunyiLyu** [comment]
@vinu1421 I tried deleting and deploying rabbitmqcluster with the same name couple times and cannot reproduce this issue. I would suggest delete this rabbitmq entirely and create a new one and see if the credentials are valid after the fresh deploy.

**Comment by vinu1421** [comment]
@ChunyiLyu, We are using a persistent disk here. I don't think the default credentials are getting updated.

**Comment by ChunyiLyu** [comment]
@ChunyiLyu That might depend on the [reclaim policy](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaim-policy) of the storage class you are using. Are your rabbit PVs are preserved and then re used when you create your new cluster? 

Also, is there a specific reason for you to 1) keep recreating your RabbitMQ clusters 2) recreating your RabbitMQ all in the same name? If you are recreating clusters because of testing, you could update the reclaim policy to delete to make sure you're are having fresh deploys. If for whatever reason you would like to keep your PVs around for your clusters, please create them in different names.

**Comment by ralphotowo** [comment]
@vinu1421 Did you find a solution to this problem? I installed the RabbitMQ Cluster Operator using the helm chart and set the default credentials within the `additionalConfig` block:

```
    additionalConfig: |
      default_user_tags.administrator = true
      default_user=admin
      default_pass=admin

```
I have the same 401 unauthorized error as you, and I see access denied errors in RabbitMQ pods:

**RabbitMQ pod logs:**
```
rabbitmq 2022-11-17 06:45:16.642222+00:00 [warning] <0.1990.0> HTTP access denied: user 'default_user_sQ8MpJ4QspHqLnOkYuH' - invalid credentials                                                       │
│ rabbitmq 2022-11-17 06:45:16.672717+00:00 [warning] <0.1992.0> HTTP access denied: user 'default_user_sQ8MpJ4QspHqLnOkYuH' - invalid credentials                                                       │
│ rabbitmq 2022-11-17 06:45:17.263185+00:00 [warning] <0.1994.0> HTTP access denied: user 'default_user_sQ8MpJ4QspHqLnOkYuH' - invalid credentials
```

**rabbitmq-messaging-topology-operator pod logs:**
```
 {"level":"info","ts":1668667598.6464272,"msg":"Start reconciling","controller":"policy","controllerGroup":"rabbitmq.com","controllerKind":"Policy","policy":{"name":"lazy-queue-policy","namespace":"r │
│ abbit-mq"},"namespace":"rabbit-mq","name":"lazy-queue-policy","reconcileID":"f6d96325-389c-4876-906b-71cb783821f6","spec":"{\"name\":\"lazy-queue-policy\",\"vhost\":\"test-vhost\",\"pattern\":\"^laz │
│ y-queue-\",\"applyTo\":\"queues\",\"definition\":{\"queue-mode\":\"lazy\"},\"rabbitmqClusterReference\":{\"name\":\"rabbitmq-staging\"}}"}                                                             │
│ {"level":"error","ts":1668667598.6532624,"msg":"failed to create Policy","controller":"policy","controllerGroup":"rabbitmq.com","controllerKind":"Policy","policy":{"name":"lazy-queue-policy","namesp │
│ ace":"rabbit-mq"},"namespace":"rabbit-mq","name":"lazy-queue-policy","reconcileID":"f6d96325-389c-4876-906b-71cb783821f6","policy":"lazy-queue-policy","error":"Error: API responded with a 401 Unauth │
│ orized","stacktrace":"github.com/rabbitmq/messaging-topology-operator/controllers.(*PolicyReconciler).Reconcile\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/src/github.com/rab │
│ bitmq/rmq-messaging-topology-operator/controllers/policy_controller.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/bitnami/blacksmith-sandox/rmq-messaging- │
│ topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandle │
│ r\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/int │
│ ernal/controller.(*Controller).processNextWorkItem\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controll │
│ er.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runti │
│ me@v0.12.3/pkg/internal/controller/controller.go:234"} 
```

**Comment by ElninosTail** [comment]
> @vinu1421 Did you find a solution to this problem? I installed the RabbitMQ Cluster Operator using the helm chart and set the default credentials within the `additionalConfig` block:
> 
> ```
>     additionalConfig: |
>       default_user_tags.administrator = true
>       default_user=admin
>       default_pass=admin
> ```
> 
> I have the same 401 unauthorized error as you, and I see access denied errors in RabbitMQ pods:
> 
> **RabbitMQ pod logs:**
> 
> ```
> rabbitmq 2022-11-17 06:45:16.642222+00:00 [warning] <0.1990.0> HTTP access denied: user 'default_user_sQ8MpJ4QspHqLnOkYuH' - invalid credentials                                                       │
> │ rabbitmq 2022-11-17 06:45:16.672717+00:00 [warning] <0.1992.0> HTTP access denied: user 'default_user_sQ8MpJ4QspHqLnOkYuH' - invalid credentials                                                       │
> │ rabbitmq 2022-11-17 06:45:17.263185+00:00 [warning] <0.1994.0> HTTP access denied: user 'default_user_sQ8MpJ4QspHqLnOkYuH' - invalid credentials
> ```
> 
> **rabbitmq-messaging-topology-operator pod logs:**
> 
> ```
>  {"level":"info","ts":1668667598.6464272,"msg":"Start reconciling","controller":"policy","controllerGroup":"rabbitmq.com","controllerKind":"Policy","policy":{"name":"lazy-queue-policy","namespace":"r │
> │ abbit-mq"},"namespace":"rabbit-mq","name":"lazy-queue-policy","reconcileID":"f6d96325-389c-4876-906b-71cb783821f6","spec":"{\"name\":\"lazy-queue-policy\",\"vhost\":\"test-vhost\",\"pattern\":\"^laz │
> │ y-queue-\",\"applyTo\":\"queues\",\"definition\":{\"queue-mode\":\"lazy\"},\"rabbitmqClusterReference\":{\"name\":\"rabbitmq-staging\"}}"}                                                             │
> │ {"level":"error","ts":1668667598.6532624,"msg":"failed to create Policy","controller":"policy","controllerGroup":"rabbitmq.com","controllerKind":"Policy","policy":{"name":"lazy-queue-policy","namesp │
> │ ace":"rabbit-mq"},"namespace":"rabbit-mq","name":"lazy-queue-policy","reconcileID":"f6d96325-389c-4876-906b-71cb783821f6","policy":"lazy-queue-policy","error":"Error: API responded with a 401 Unauth │
> │ orized","stacktrace":"github.com/rabbitmq/messaging-topology-operator/controllers.(*PolicyReconciler).Reconcile\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/src/github.com/rab │
> │ bitmq/rmq-messaging-topology-operator/controllers/policy_controller.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/bitnami/blacksmith-sandox/rmq-messaging- │
> │ topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandle │
> │ r\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/int │
> │ ernal/controller.(*Controller).processNextWorkItem\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controll │
> │ er.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runti │
> │ me@v0.12.3/pkg/internal/controller/controller.go:234"} 
> ```

@ralphotowo, Any success?
Having the same kind of error as you.

I can access RabbitMQ from (GUI) console  but unable to do so from my command line / API.

Error writing to rabbitmq/config/connection: Error making API request.

URL:  PUT https://secrets....../rabbitmq/config/connection
code: 500. Errors:

* 1 error occurred:
          * Failed to validate the connection: Error 401 (not_authorised): Login failed.

**Comment by duclm2609** [comment]
I have the same issue. I can loging to the Management Web UI using default user, but the messaging topology operator failed to create user with 401 Unauthorized message.

**Comment by ElninosTail** [comment]
@duclm2609 ,  I haven't been able to resolve the issue myself.
What's the procedure for escalating matters like this?

**Comment by duclm2609** [comment]
Just hope someone in the team read this and provide some hint. I'm unable to resolve too.

**Comment by ElninosTail** [comment]
@duclm2609 , Are you using hashicorp Vault to generate secrets?

**Comment by duclm2609** [comment]
Nope. I hard code the default user in the YAML config file, just like @ralphotowo

**Comment by ElninosTail** [comment]
what  version of RabbitMQ?
I'm using 3.8.23.

**Comment by duclm2609** [comment]
I used operator Helm chart by Bitnami version 3.1.4. It installs RabbitMQ version 3.10.11: docker.io/bitnami/rabbitmq:3.10.11-debian-11-r4

**Comment by lukebakken** [comment]
@ElninosTail RabbitMQ 3.8.x is completely out of support.

**Comment by duclm2609** [comment]
I just found a note on documentation of the Messaging Topology Operator said that:

> It uses the generated default user secret from RabbitmqCluster (set in rabbitmqcluster.status.binding) to authenticate with RabbitMQ server. If your RabbitmqCluster is deployed with import definitions or provided default user credentials, the default user secret from rabbitmqcluster.status.binding may not be correct and Messaging Topology Operator will fail with authentication error.

From what I understand is that if you configure default user in config file, the Topology Operator cannot authorize with broker server.

**Comment by vinu1421** [comment]
@ralphotowo @ElninosTail @duclm2609 
I had the same issue and I was able to resolve it.  I have created a secret named rabbitmq-default-user deployed it initially before deploying the rabbitMQ and Topology operator.

```
apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-default-user
stringData:
    default_user.conf: |
        default_user = rabbit_admin
        default_pass = hhshgsgtehebc
    password: hhshgsgtehebc
    username: rabbit_admin
```
username and password is required if using topology operator, as it is using these to connect with the rabbitmq cluster. 

Our setup was that we are using PV and hence the default credential created will be saved and when the cluster is re-create the secret changes but the old credentials stays there, but the topology operator tries to get the credentials from the new secret and eventually gets 401 error. With above method this issue as been resolved.

**Comment by MonicaMagoniCom** [comment]
> @ralphotowo @ElninosTail @duclm2609 I had the same issue and I was able to resolve it. I have created a secret named rabbitmq-default-user deployed it initially before deploying the rabbitMQ and Topology operator.
> 
> ```
> apiVersion: v1
> kind: Secret
> metadata:
>     name: rabbitmq-default-user
> stringData:
>     default_user.conf: |
>         default_user = rabbit_admin
>         default_pass = hhshgsgtehebc
>     password: hhshgsgtehebc
>     username: rabbit_admin
> ```
> 
> username and password is required if using topology operator, as it is using these to connect with the rabbitmq cluster.
> 
> Our setup was that we are using PV and hence the default credential created will be saved and when the cluster is re-create the secret changes but the old credentials stays there, but the topology operator tries to get the credentials from the new secret and eventually gets 401 error. With above method this issue as been resolved.

I had the same issue and this proposed solution solved it! thanks

**Comment by hprashar** [comment]
Don't add default user (using additional config in the manifest) while setting up RabbitmqCluster as message operator uses the generated default user secret from RabbitmqCluster (set in rabbitmqcluster.status.binding) to authenticate with RabbitMQ server. Instead add a new user using the vhost crd added by the message operator. Please see the example below. This worked for me. 

`---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: mq-sailgpsim
  namespace: ray
spec:
  replicas: 1
  resources:
    requests:
      cpu: 2000m
      memory: 2Gi
    limits:
      cpu: 4000m
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      log.console.level = debug
---
apiVersion: v1
kind: Secret
metadata:
  name: ha-users-2
  namespace: ray
type: Opaque
stringData:
  username: guest
  password: guest
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: replicator-hare
  namespace: ray
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: mq-sailgpsim
  importCredentialsSecret:
    name: ha-users-2
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: sim
  namespace: ray
spec:
  name: sim
  rabbitmqClusterReference:
    name: mq-sailgpsim
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: sim.default.all
  namespace: ray
spec:
  vhost: "sim"
  userReference:
    name: replicator-hare
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: mq-sailgpsim
`
