### ISSUE TITLE
Examples should not encourage optional queue argument use

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/messaging-topology-operator#40]
[This example](https://github.com/rabbitmq/messaging-topology-operator/blob/main/docs/examples/queues/quorum-queue.yaml#L15) encourages declaration of [optional queue arguments](https://www.rabbitmq.com/queues.html#optional-arguments). We should not do this. For everything that is supported by [policies](https://www.rabbitmq.com/parameters.html#why-policies-exist), policies should be used.

Optional queue arguments are only needed to specify a queue type since that cannot be changed at runtime and policies take effect after queue declaration and startup.

**Comment by ChunyiLyu** [comment]
Sure. I deleted it: https://github.com/rabbitmq/messaging-topology-operator/commit/ce9ec78e7517809adc91490bfb6ff54133cba5e1
