### ISSUE TITLE
Allow for autogenerating passwords while pre-defining usernames on User objects

### ISSUE THREAD

**Issue by coro** [rabbitmq/messaging-topology-operator#466]
**Is your feature request related to a problem? Please describe.**
Currently, in order to predefine the RabbitMQ username for a `User` object, you must provide it in a credentials Secret. However, you must also provide a pre-defined password at the same time.

**Describe the solution you'd like**
The ability to pre-define a username for a created user, but allow the password to be autogenerated.
In addition, it would be useful to only have to create a single object per user, rather than a User and a Secret.

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/rabbitmq/messaging-topology-operator/discussions/465

**Comment by bigbosst** [comment]
Generally you need to use Helm to define a secret on the fly. I have also found an interesting project that allows you to call it's operator and have it generate a random secret from a standard yaml: https://github.com/mittwald/kubernetes-secret-generator

**Comment by ChunyiLyu** [comment]
The current workflow for a pre-defined username and password is via providing a secret in `spec. importCredentialsSecret`, and the operator expects both keys `username` and `password` to be there. Perhaps we can allow only the `username` being defined in the secret and generated password if that's the case? This way there is no change the CRD structure itself and avoid storing usernames (sensitive information) in manifest.

**Comment by DanielePalaia** [comment]
Functionality implemented in https://github.com/rabbitmq/messaging-topology-operator/pull/483

Closing this one.
