### ISSUE TITLE
Headers Bindings Example

### ISSUE THREAD

**Issue by jeffreywstevens** [rabbitmq/messaging-topology-operator#507]
**For questions**, please start a discussion in [RabbitMQ Discussions](https://github.com/rabbitmq/rabbitmq-server/discussions)
or send an email to [RabbitMQ Mailing list](https://groups.google.com/g/rabbitmq-users), stating that your question is regarding
RabbitMQ Cluster Operator.

There's also a `#kubernetes` channel in [RabbitMQ community Slack](https://rabbitmq-slack.herokuapp.com/).

Is there an example of a messaging topology binding using a headers exchange?

**Comment by DanielePalaia** [comment]
Hi @jeffreywstevens currently there is no example here in the repo as we have an example for direct and one for fanout https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/exchanges
and topic:
https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/examples/topic-exchanges

Are you having any issue creating a header one?

**Comment by jeffreywstevens** [comment]
I was able to use the CRD’s to find the correct properties to set.
