### ISSUE TITLE
Scope operator interaction to namespace

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/messaging-topology-operator#51]
Looking at the `RabbitmqClusterReference` property in `User` kind:

https://github.com/rabbitmq/messaging-topology-operator/blob/06637f5b9fbacefce0ca2334577effd610c7a9eb/api/v1alpha1/user_types.go#L18-L33

https://github.com/rabbitmq/messaging-topology-operator/blob/06637f5b9fbacefce0ca2334577effd610c7a9eb/api/v1alpha1/queue_types.go#L44-L49

I noticed that we allow to interact with `RabbitmqCluster` objects in any namespace in the cluster. I'm concerned that we might be allowing a human user `Cody` to create RabbitMQ primitives in a RabbitMQ cluster they might not have access to. For example, `Cody` has access only to namespace `cody-dev` and they create a `User` kind which references a `RabbitmqCluster` with name `rabbit` in namespace `foobar`. The topology operator will create the user primitive in RabbitMQ, granting `Cody` credentials to access said RabbitMQ instance. 

My concern is that the operator might allow `Cody` to access RabbitMQ instances they are not supposed or intended to.

Should we remove the `namespace` aspect, effectively having a `LocalObjectReference`-like object?

**Comment by MirahImage** [comment]
This is a breaking change to the API, therefore we need to bump the API version to v1alpha2 (issue #63)

**Comment by coro** [comment]
Just to clarify, this affects all topology objects, which all allow for a namespace field in the cluster reference.

**Comment by coro** [comment]
@n3wscott How would this proposed change affect knative?
