### ISSUE TITLE
ARM64 Support not working, possible build issue

### ISSUE THREAD

**Issue by InariTheFox** [rabbitmq/messaging-topology-operator#570]
## Describe the bug
Deploying the messaging topology operator image to an ARM64 cluster fails with the error: "exec format error".

## To Reproduce
- Execute  kubectl apply -f https://github.com/rabbitmq/messaging-topology-operator/releases/latest/download/messaging-topology-operator-with-certmanager.yaml
- Get state of deployment.
- Examine pod.
- Pod is in CrashLoopback.
- Examine logs.
- Logs show "exec format error" as only message.

**Expected behavior**
Pod should deploy successfully.

## Version and environment information
- Messaging Topology Operator: 1.10.1
- RabbitMQ: 3.10.2
- RabbitMQ Cluster Operator: 2.1.0
- Kubernetes: 1.24.10
- Cloud provider or hardware configuration: Rancher on custom AWS R6G series three node cluster.
 
## Additional context
See [[issues/521]](https://github.com/rabbitmq/messaging-topology-operator/issues/521)

I have additionally tried copying the yaml file locally and setting to arm64 specific tags with no luck.

I suspect that the ARM images aren't valid ARM64 images. If you inspect the tags on docker hub, you'll notice that the file sizes are identical between the amd64 and arm64 versions in the tags. But if you inspect the tags with the cluster-operator images the arm64 and amd64 images are different sizes.

**Comment by DanielePalaia** [comment]
Hi @InariTheFox Can you try with the last operator release? We made some modifications recently https://github.com/rabbitmq/messaging-topology-operator/pull/572 on the arm64 deployment process which may solve this issue.

**Comment by DanielePalaia** [comment]
@InariTheFox Yes I can see the same issue you have. In the logs of the messaging topology operator  pod I have
exec /manager: exec format error

Apparently it also complains about:
MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found
even if is there (I can see it with kubectl get secret)

Strange things are:
1) The image is built using github actions, we use the same approach for cluster-operator and for cluster-operator is working without issue
2) If I pull the image in an arm machine with:

daniele@arm-machine-test:~$ sudo docker inspect docker.io/rabbitmqoperator/messaging-topology-operator:1.10.2 | grep "Architecture"
        "Architecture": "arm64",
So it seems correctly built for arm64.

I'm wondering if it is something that can be related to the cert-manager.

**Comment by DanielePalaia** [comment]
I think it may be due to the Dockerfile not updated for this operator: https://github.com/rabbitmq/messaging-topology-operator/blob/main/Dockerfile

**Comment by ChunyiLyu** [comment]
@InariTheFox New release cut with this change: https://github.com/rabbitmq/messaging-topology-operator/releases/tag/v1.11.0
