### ISSUE TITLE
Create `policies.rabbitmq.com` for queues with queue argument

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/messaging-topology-operator#59]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zerpet** [comment]
Something to be aware of is that only one policy can be active at a time. One option would be to create a policy with an exact match of the queue name; this would create a 1-1 relationship between a queue and a policy. It should be fine, but I'm not sure if policies were designed or intended to be used in this way (for each queue, one policy).

**Comment by ChunyiLyu** [comment]
Done! https://github.com/rabbitmq/messaging-topology-operator/pull/46

**Comment by ChunyiLyu** [comment]
Don't think this makes sense considering policies are generally used to manage/configure a set of queues. Closing this issue for now.
