### ISSUE TITLE
Add Default Queue Type for Vhosts

### ISSUE THREAD

**Issue by jbexten** [rabbitmq/messaging-topology-operator#608]
RabbitMQ is deprecating the use of classic queues in favor of quorum. The suggested migration strategy is to set up new vhosts with a default queue type parameter set to quorum. This allows for seamless migration and federation between classic queues and quorum queues. https://blog.rabbitmq.com/posts/2023/02/quorum-queues-migration/

I'm not experienced in GO so I don't have a pull request right now. Could the vhost spec be updated easily to send the DefaultQueueType to RabbitHole?

Thank You

**Comment by ChunyiLyu** [comment]
rabbithole is updated as part of: https://github.com/rabbitmq/messaging-topology-operator/pull/620
Working on this and PR is coming soon

**Comment by ChunyiLyu** [comment]
@jbexten New release cut with this change: https://github.com/rabbitmq/messaging-topology-operator/releases/tag/v1.11.0
