### ISSUE TITLE
Order of CRD apply's causes Binding CRD's to fail

### ISSUE THREAD

**Issue by MarkCupitt** [rabbitmq/messaging-topology-operator#610]
## Describe the bug
When we deploy a bunch of queues, exchanges etc, the topology operator seems to reconcile bindings first then queues and exchanges, but the binding will fail because the exchange does not exist

Deployment is done by sending a bunch of yamal using kubectl apply

I'm not sure if there is a way to influence this. We can manage it by deploying everything except bindings, waiting util reconciliation is complete, then applying th ebindings.

This is a real pain for our automated deployment

I would have expected the operator to attempt to reconcile them again, that does not appear to be the case

Suggested Fixes

Have the operator conduct additional reconciliation steps

Change the order of reconciliation to make sure bindings are done last

**Comment by MarkCupitt** [comment]
@ChunyiLyu The only thought I have is that I created them all in a single kubectl apply statement. The order of the apply was 
 6 x Exchange, 10 x Queues and 31 x Bindings  and the all the binding status's did show an error, that the queue did not exist. My thought was that the issue may have been due to all being in the same reconciliation pass, where the queue was in the process of being created and the bindings were being created when the queue was still being created, possibly multiple threads? 
 
If you cannot replicate, please ping me back and I will try to be a bit more scientific and recreate and document in detail, and send you the yaml and logs, Im a bit loaded at the moment, but will try and make some time if necessary as would love to see this resolved.

**Comment by MarkCupitt** [comment]
@ChunyiLyu I tried to recreate the issue and seemed to have failed to do so, which is weird, there does seem to be an issue with permissions in the topology operator, however .. 

Here is what I did, the only difference is that this was not a clean install from scratch, I deleted a running systems Crd's (including the cluster), waited 10 minutes, Restarted the operator and topology operator, then deployed in order listed below.

Note, in topology operator logs, there some errors related to permissions and cluster not existing form deleting all the crds

The Bindings did fail, but THEN it DID create the bindings, this is not what happened when we reported the issue .. weird .. 

Attached the Operator and topology-operator logs as well, they may be of use 

```
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.account.blockingstate created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.account.change created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.account.create created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.account.overduechange created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.bundle.blockingstate created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.bundle.pause created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.bundle.resume created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.invoice.adjustment created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.invoice.create created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.invoice.notification created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.invoice.payment.failed created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.invoice.payment.sucess created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.payment.failed created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.payment.refund created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.payment.success created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.bcdchange created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.n
[messaging-topology-operator-865fc8dfcc-6gb45.log](https://github.com/rabbitmq/messaging-topology-operator/files/11482924/messaging-topology-operator-865fc8dfcc-6gb45.log)
otification.subscription.bundle.blockingstate created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.bundle.pause created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.bundle.resume created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.cancel created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.change created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.create created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.entitlement.cancel created
binding.rabbitmq.com/binding-events-event.killbill.queu
[rabbitmq-cluster-operator-54697d5bc6-fgzgn.log](https://github.com/rabbitmq/messaging-topology-operator/files/11482926/rabbitmq-cluster-operator-54697d5bc6-fgzgn.log)
e-event.notification.subscription.entitlement.create created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.phase created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.subscription.uncancel created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.tenant.field.create created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.tenant.field.delete created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.tenant.kvs.configchange created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.tenant.kvs.configdelete created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.tenant.tag.create created
binding.rabbitmq.com/binding-events-event.killbill.queue-event.notification.tenant.tag.delete created
binding.rabbitmq.com/binding-minio-minio.active.notification-minio.active.notification created
binding.rabbitmq.com/binding-tenant-tenant.files-tenant.files.config created
binding.rabbitmq.com/binding-tenant-tenant.files-tenant.files.transactions created
binding.rabbitmq.com/binding-tenant-tenant.notify-tenant.notify created
binding.rabbitmq.com/binding-tenant-tenant.search-tenant.search.create created
binding.rabbitmq.com/binding-tenant-tenant.search-tenant.search.delete created
binding.rabbitmq.com/binding-tenant-tenant.search-tenant.search.update created
exchange.rabbitmq.com/account.exchange created
exchange.rabbitmq.com/events.exchange created
exchange.rabbitmq.com/mail.exchange created
exchange.rabbitmq.com/messaging.exchange created
exchange.rabbitmq.com/minio.exchange created
exchange.rabbitmq.com/tenant.exchange created
[rabbitmq-cluster-operator-54697d5bc6-fgzgn.log](https://github.com/rabbitmq/messaging-topology-operator/files/11482925/rabbitmq-cluster-operator-54697d5bc6-fgzgn.log)

permission.rabbitmq.com/rabbit-user-permission-bonanza unchanged
permission.rabbitmq.com/rabbit-user-permission-developer unchanged
permission.rabbitmq.com/rabbit-user-permission-rabbit unchanged
queue.rabbitmq.com/event.killbill.queue created
queue.rabbitmq.com/mail.message.bounce created
queue.rabbitmq.com/mail.message.error created
queue.rabbitmq.com/mail.message.inbound created
queue.rabbitmq.com/mail.message.outbound created
queue.rabbitmq.com/minio.active.notification created
queue.rabbitmq.com/tenant.files created
queue.rabbitmq.com/tenant.notify created
queue.rabbitmq.com/tenant.search created
queue.rabbitmq.com/tenant.update created
rabbitmqcluster.rabbitmq.com/rabbit-bonanza created
user.rabbitmq.com/rabbit-user-bonanza created
user.rabbitmq.com/rabbit-user-developer created
user.rabbitmq.com/rabbit-user-rabbit created
vhost.rabbitmq.com/vhost-bonanza created
```

[messaging-topology-operator-865fc8dfcc-6gb45.log](https://github.com/rabbitmq/messaging-topology-operator/files/11482927/messaging-topology-operator-865fc8dfcc-6gb45.log)
[rabbitmq-cluster-operator-54697d5bc6-fgzgn.log](https://github.com/rabbitmq/messaging-topology-operator/files/11482932/rabbitmq-cluster-operator-54697d5bc6-fgzgn.log)

**Comment by MarkCupitt** [comment]
My only thought is that we create the cluster as well in the same batch of yaml, perhaps some weird timing came into play on the clean install on a new system, PV creation or whatever??

**Comment by ChunyiLyu** [comment]
@MarkCupitt If the RMQ cluster isn't ready yet, binding/queue/exchange or any topology object creation requests will fail, but the request should be requeued and everything should be reconcile in the end (given the RMQ cluster does become ready at some point). I'm not sure what's the reason for what you've saw earlier.

Even though it will work, I would recommend waiting for the cluster to be ready first then create any topology resources. You can check the status condition of the rabbitmq cluster for such information, for example:

```
status:
  conditions:
  - lastTransitionTime: "2023-05-18T05:33:38Z"
    reason: AllPodsAreReady
    status: "True"
    type: AllReplicasReady
  - lastTransitionTime: "2023-05-18T05:33:38Z"
    reason: AtLeastOneEndpointAvailable
    status: "True"
    type: ClusterAvailable
...
```
`ClusterAvailable` means at least one node (pod) has become ready and `AllPodsAreReady` is true only when all nodes (pods) are ready.
