### ISSUE TITLE
Bump API version to v1alpha2

### ISSUE THREAD

**Issue by coro** [rabbitmq/messaging-topology-operator#63]
The upcoming release will contain breaking changes to the User object Spec. In particular, the field `User.Spec.Name` is removed, and the username for a User is now autogenerated randomly. Users have the option to pre-define the username & password of a created User by providing a Secret containing these credentials at create time.

## Checklist
[] API version bumped to v1alpha2
[] Unit & system tests pass
[] Release notes for upcoming release detail removal of v1alpha1
[] (If not supporting upgrades from operator v0.3.0) Release notes detail migration procedure or mitigation

**Comment by ChunyiLyu** [comment]
Finished as part of: https://github.com/rabbitmq/messaging-topology-operator/pull/83
