### ISSUE TITLE
error says srcUri not found if destUri is not found

### ISSUE THREAD

**Issue by SGStino** [rabbitmq/messaging-topology-operator#634]
https://github.com/rabbitmq/messaging-topology-operator/blob/2c5e17f9a8896c816ac80ce9ab5825a91a8ef342/controllers/shovel_controller.go#L54

I've just ran into this while trying to configure a shovel, and i kept wondering why it couldn't find srcUri (which was there), but i had dstUri instead of destUri, which is where the error is coming from.

**Comment by ChunyiLyu** [comment]
@SGStino Good catch. Thanks for reporting!
