### ISSUE TITLE
Topology operator to be allowed only to selected namespaces

### ISSUE THREAD

**Issue by envycz** [rabbitmq/messaging-topology-operator#684]
**Is your feature request related to a problem? Please describe.**
I would like to be able to restrict Topology Operator integrations only to selected namespaces so it won't need to have cluster wide roles assigned. 

**Describe the solution you'd like**
It would be great if I could restrict Topology Operator with a OPERATOR_SCOPE_NAMESPACE env variable similarly as I can with the Cluster Operator. No cluster roles would be necessary with this set up. 

**Describe alternatives you've considered**
I understand that Topology Operator by default won't interact with created resources in namespaces where RabbitMQCluster resource is not present, but then why it's not enough to see this specific resources on cluster wide scope? Is it really necessary to give this operator also cluster wide permissions for events, secrets and services?

**Additional context**
I tried to find possible solutions everywhere but didnt find anything so I'm sorry if I missed something. I currently work on a project with tight security standards and any cluster wide permissions in k8s clusters are raising questions. Thank you in advance for any responses.

**Comment by MirahImage** [comment]
I believe this functionality is already present in the operator, even if undocumented. See https://github.com/rabbitmq/messaging-topology-operator/blob/96228a0eb50999647ba3fbccca51a1bdc96ff03f/main.go#L101

**Comment by envycz** [comment]
@MirahImage wow it actually works, thanks!
